# Example KiBot config file
kibot:
  version: 1

preflight:
  run_erc: true
  update_xml: true
  run_drc: true
  check_zone_fills: true
  ignore_unconnected: false

outputs:
  - name: 'interactive_bom'
    comment: "Interactive Bill of Materials (HTML)"
    type: ibom
    dir: BoM
    options:
      blacklist: 'DNF*'
      name_format: '%f_%r_iBoM'

  - name: 'bom_csv'
    comment: "Bill of Materials in CSV format"
    type: kibom
    dir: BoM
    options:
      format: CSV  # HTML or CSV

  - name: 'gerbers'
    comment: "Gerbers for the board house"
    type: gerber
    dir: gerber
    options:
      # generic layer options
      exclude_edge_layer: true
      exclude_pads_from_silkscreen: true
      use_aux_axis_as_origin: false
      plot_sheet_reference: false
      plot_footprint_refs: true
      plot_footprint_values: true
      force_plot_invisible_refs_vals: false
      tent_vias: false

      # gerber options
      line_width: 0.1
      subtract_mask_from_silk: false
      use_protel_extensions: true
      gerber_precision: 4.6
      create_gerber_job_file: false
      use_gerber_x2_attributes: false
      use_gerber_net_attributes: false

    # for 2-layer pcb
    layers:
      - layer: F.Cu
        suffix: F_Cu
      - layer: B.Cu
        suffix: B_Cu
      - layer: F.Paste
        suffix: F_Paste
      - layer: B.Paste
        suffix: B_Paste
      - layer: F.SilkS
        suffix: F_SilkS
      - layer: B.SilkS
        suffix: B_SilkS
      - layer: F.Mask
        suffix: F_Mask
      - layer: B.Mask
        suffix: B_Mask
      - layer: Edge.Cuts
        suffix: Edge_Cuts

  - name: "Excellon drills"
    comment: "Excellon drill files"
    type: "excellon"
    dir: "gerber"
    options:
      use_aux_axis_as_origin: true
      metric_units: true
      pth_and_npth_single_file: false
      minimal_header: true
      mirror_y_axis: false
