# This is a basic workflow to help you get started with Actions

name: KiCad-exports

on:
  push:
    paths:
    - '**.sch'
    - '**.kicad_pcb'
  pull_request:
    paths:
      - '**.sch'
      - '**.kicad_pcb'

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nerdyscout/kicad-exports@v2.1
      with:
      # Required - kibot config file
        config: ./config/docs.kibot.yaml
      # optional - prefix to output defined in config
        dir: docs
      # optional - schematic file
        schema: '*.sch'
      # optional - PCB design file
        board: '*.kicad_pcb'
    - uses: nerdyscout/kicad-exports@v2.1
      with:
      # Required - kibot config file
        config: ./config/fabrications.kibot.yaml
      # optional - prefix to output defined in config
        dir: gerber
      # optional - schematic file
        schema: '*.sch'
      # optional - PCB design file
        board: '*.kicad_pcb'
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: |
          docs/docs
          !docs/docs/*.ogv
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: gerber
        path: gerber/gerber
